
services:
  db:
    image: postgres:15
    container_name: geodb
    environment:
      POSTGRES_USER: django_user      # 100% ASCII
      POSTGRES_PASSWORD: django_pass  # 100% ASCII
      POSTGRES_DB: geodb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
